import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Tanha = localFont({
  src: "./fonts/Tanha.woff",
});
const Tanha2 = localFont({
  src: "./fonts/Tanha.woff2",
});
const TanhaDigit = localFont({
  src: "./fonts/Tanha-FD.woff",
});
const TanhaDigit2 = localFont({
  src: "./fonts/Tanha-FD.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        style={{ direction: "rtl" }}
        className={`${Tanha.className} ${Tanha2.className} ${TanhaDigit.className} ${TanhaDigit2.className}`}
      >
        {children}
      </body>
    </html>
  );
}
