import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Tanha = localFont({
  src: [
    { path: "./fonts/Tanha.woff", weight: "400" },
    { path: "./fonts/Tanha.woff2", weight: "700" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={Tanha.className}>
        {children}
      </body>
    </html>
  );
}
